{% set name = "utool" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/utool-{{ version }}.tar.gz
  sha256: 793e1889cb7b2e8ba30ed145512a96536b52b70bae3eae0117096e28fada66eb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six
    - timerit

test:
  imports:
    - utool
    - utool._internal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Erotemic/utool
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Useful Utility Tools For You!
  description: |
    The utool library is a collection of tools that I've found useful.
    I've written most of them from scratch, but there are a few I've
    taken or partially taken from StackOverflow. References are given
    in most locations.
  doc_url: https://github.com/Erotemic/utool
  dev_url: https://github.com/Erotemic/utool

extra:
  recipe-maintainers:
    - jan-janssen
