schema_version: 1

context:
  name: utool
  version: "2.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/utool-${{ version }}.tar.gz
  sha256: 46ddc6fb7703d357353383a274af36733a1b6832d8b3cbc7e81f471f563f706c

build:
  number: 3
  skip: win
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python
  run:
    - python
    - six
    - timerit
    - loguru
    - numpy
    - gitpython
    - networkx
    - pandas
    - parse
    - pyparsing
    - pytz
    - requests
    - ubelt

tests:
  - python:
      imports:
        - utool
        - utool._internal
      pip_check: true

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Useful Utility Tools For You!
  description: |
    The utool library is a collection of tools that I've found useful.
    I've written most of them from scratch, but there are a few I've
    taken or partially taken from StackOverflow. References are given
    in most locations.
  homepage: https://github.com/Erotemic/utool
  repository: https://github.com/Erotemic/utool
  documentation: https://github.com/Erotemic/utool

extra:
  recipe-maintainers:
    - jan-janssen
